CREATE TABLE orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  productId INTEGER NOT NULL,
  productName TEXT NOT NULL,
  size TEXT NOT NULL,
  fullName TEXT NOT NULL,
  phone TEXT NOT NULL,
  city TEXT NOT NULL,
  price REAL NOT NULL,
  date TEXT NOT NULL
);