name = "product-website"
compatibility_date = "2025-02-10"
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "client-details2"
database_id = "b58b78b2-4740-42e1-899d-df12d554d6e4"