name = "sales-analytics-worker"
main = "worker.ts"
compatibility_date = "2023-05-18"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "database1"
database_id = "2d3a650f-a72b-4d63-ba43-5bdf41e7239f"