export const products = [
  {
    id: 1,
    name: "ANIME BLACK SHIRT",
    price: 100,
    theme: "anime",
    mainImage: "/images/shirt.png",
    alternativeImages: ["/images/gym.jpg", "/images/shirt-alt2.png", "/images/shirt-alt3.png"],
    category: "totebags",
  },
  {
    id: 2,
    name: "GOOSEPUMP CAP",
    price: 80,
    theme: "art",
    mainImage: "/images/hoodie-bac.png",
    alternativeImages: ["/images/shirt.png", "/images/hoodie-alt2.png", "/images/hoodie-alt3.png"],
    category: "caps",
  },
  {
    id: 3,
    name: "ANIME DESIGN HOODIE BLACK",
    price: 279,
    theme: "anime",
    mainImage: "/images/hoodie-bac.png",
    alternativeImages: ["/images/hoodie-alt1.png", "/images/hoodie-alt2.png", "/images/hoodie-alt3.png"],
    category: "hoodies",
  },
  {
    id: 4,
    name: "GYM BEAST MODE HOODIE",
    price: 279,
    theme: "gym",
    mainImage: "/images/hoodie-bac.png",
    alternativeImages: ["/images/hoodie-alt1.png", "/images/hoodie-alt2.png", "/images/hoodie-alt3.png"],
    category: "hoodies",
  },
  {
    id: 5,
    name: "RAP CULTURE HOODIE",
    price: 279,
    theme: "rap",
    mainImage: "/images/hoodie-bac.png",
    alternativeImages: ["/images/hoodie-alt1.png", "/images/hoodie-alt2.png", "/images/hoodie-alt3.png"],
    category: "hoodies",
  },
  {
    id: 6,
    name: "MOVIE CLASSICS HOODIE",
    price: 279,
    theme: "movies",
    mainImage: "/images/hoodie-bac.png",
    alternativeImages: ["/images/shirt.png", "/images/hoodie-alt2.png", "/images/hoodie-alt3.png"],
    category: "hoodies",
  },
  {
    id: 7,
    name: "ARTISTIC TOTE BAG",
    price: 150,
    theme: "art",
    mainImage: "/images/shirt.png",
    alternativeImages: ["/images/gym.jpg", "/images/shirt-alt2.png", "/images/shirt-alt3.png"],
    category: "totebags",
  },
  {
    id: 8,
    name: "RETRO GAMING T-SHIRT",
    price: 120,
    theme: "gaming",
    mainImage: "/images/shirt.png",
    alternativeImages: ["/images/gym.jpg", "/images/shirt-alt2.png", "/images/shirt-alt3.png"],
    category: "tshirts",
  },
  {
    id: 9,
    name: "URBAN STYLE CAP",
    price: 95,
    theme: "urban",
    mainImage: "/images/cap.png",
    alternativeImages: ["/images/shirt.png", "/images/hoodie-alt2.png", "/images/hoodie-alt3.png"],
    category: "caps",
  },
  {
    id: 10,
    name: "VINTAGE TOTE BAG",
    price: 165,
    theme: "vintage",
    mainImage: "/images/shirt.png",
    alternativeImages: ["/images/gym.jpg", "/images/shirt-alt2.png", "/images/shirt-alt3.png"],
    category: "totebags",
  },
  {
    id: 11,
    name: "STREETWEAR T-SHIRT",
    price: 135,
    theme: "urban",
    mainImage: "/images/shirt.png",
    alternativeImages: ["/images/gym.jpg", "/images/shirt-alt2.png", "/images/shirt-alt3.png"],
    category: "tshirts",
  },
  {
    id: 12,
    name: "MUSIC LOVER HOODIE",
    price: 289,
    theme: "music",
    mainImage: "/images/hoodie-bac.png",
    alternativeImages: ["/images/hoodie-alt1.png", "/images/hoodie-alt2.png", "/images/hoodie-alt3.png"],
    category: "hoodies",
  },
]

export const categories = [
  { id: "tshirts", name: "T-Shirts" },
  { id: "hoodies", name: "Hoodies" },
  { id: "totebags", name: "Tote Bags" },
  { id: "caps", name: "Caps" },
]

export const themes = [
  { id: "anime", name: "Anime" },
  { id: "gym", name: "Gym" },
  { id: "movies", name: "Movies" },
  { id: "rap", name: "Rap" },
  { id: "art", name: "Art" },
  { id: "gaming", name: "Gaming" },
  { id: "urban", name: "Urban" },
  { id: "vintage", name: "Vintage" },
  { id: "music", name: "Music" },
]

